### PR TITLE
Appropriately rescale raw signals in AnalogSignalFromNeoRawIOSource

### PR DESCRIPTION
**Pull request by jpgill86**
@samuelgarcia, since this was a simple thing to add, I'm wondering if you had a reason for leaving this out. Your comment that I removed suggested you might have been thinking of doing something more complicated. I'm finding the naive solution performs very well for my data sets. Perhaps you had concerns about performance?

### CODE REVIEW

**Comment by samuelgarcia** [comment]
I have in mind for a long long time this: 
  * neo do rescaling sig1 = raw_sig*scale1 + offset1
  * ephyviewer do rescalling sig_viewed = (sig1 * scale2) + offset2

We could do the two scalling at the same time!! 
Because now with neo.rawio we are externally ware of the scale applyed by neo.
With would save CPU and memory.

And the very best would to do this directly in GPU (with vispy) but this is another story.

It is a big path a plan to do one day :)
Nevertheless we can remove this comments.

**Comment by samuelgarcia** [comment]
Note : we should do this only for scale_mode='real_scale'.

Because for fake scale we don't mind the real scaling.

**Comment by jpgill86** [comment]
So that would be something like, in [this branch](https://github.com/NeuralEnsemble/ephyviewer/blob/54203d2a109c9a1f6c19c4525b9e7d5747ac0052/ephyviewer/traceviewer.py#L146) of `TraceViewer_ParamController.compute_rescale`, changing the existing code to this:

```python
if scale_mode=='real_scale':
    if isinstance(self.viewer.source, AnalogSignalFromNeoRawIOSource):
        gains = self.viewer.source.neorawio.header['signal_channels']['gain']
        offsets = self.viewer.source.neorawio.header['signal_channels']['offset']
    self.viewer.params['ylim_min'] = np.nanmin(self.signals_min[self.visible_channels] * gains[self.visible_channels] + offsets[self.visible_channels])
    self.viewer.params['ylim_max'] = np.nanmax(self.signals_max[self.visible_channels] * gains[self.visible_channels] + offsets[self.visible_channels])
```

I've got this running locally and it seems to work.

I have a slight preference for using `rescale_signal_raw_to_float` because of the unusual way I use ephyviewer. I keep my several signals in one TraceViewer (because that's more space efficient and seems to refresh faster), and so I have to use the `by_channel` scale mode so they don't stack up. I want `rescale_signal_raw_to_float` to be used even in this mode because I next manually set my gains and offsets so that I can view a pre-determined plot range, specified in terms of the real signal units. If `rescale_signal_raw_to_float` is removed from `AnalogSignalFromNeoRawIOSource.get_chunk`, I'll have to do the extra work to find the correct gains myself. Perhaps that's not such a bad thing. My use case is, I suppose, rather unusual.

Another small consideration is this: If I were a non-expert user and I launched ephyviewer in `real_scale` mode, I would see these seemingly arbitrary scale and offset values, instead of 1 and 0 like they would see with `rescale_signal_raw_to_float`. Maybe that would be confusing? Maybe it's not a big deal?

What do you think? Should I push the `real_scale` changes shown above?

**Comment by jpgill86** [comment]
> Because for fake scale we don't mind the real scaling.

Right. And if we keep `rescale_signal_raw_to_float` as it is in `AnalogSignalFromNeoRawIOSource.get_chunk`, extra unnecessary rescaling calculations are being done whenever we're in `same_for_all` or `by_channel` scale mode.

**Comment by jpgill86** [comment]
> And the very best would to do this directly in GPU (with vispy) but this is another story.

This is certainly something I'm unfamiliar with right now!

**Comment by samuelgarcia** [comment]
Hi again.
I read it very fastly and I thin think it is not excatly what I had in mind.
I will back on this soon.

**Comment by jpgill86** [comment]
@samuelgarcia, could you take another look at this when you have time? This is the one difference between the master branch and my fork that is needed for my app. If we can merge it and then create a release, installation of the app will be easier.

**Comment by samuelgarcia** [comment]
Oups. Sorry I forgot about this.
Could you make a PR with your other branch so I could could see immediatly diff ?

**Comment by jpgill86** [comment]
Sure, give me a could minutes.

**Comment by jpgill86** [comment]
We're going instead with the more conservative solution in #56, which restricts the expensive rescaling calculation to ``real_scale`` mode only. It was already been merged.

This PR claims to have been merged because #56 built on top of it. However, the changes in this PR were undone in another commit in that PR, so these changes don't really appear in the new code.

**Comment by samuelgarcia** [comment]
OK.
Tanks.

**Pull request merged**
