### PR TITLE
Update docs style, add badges and screenshot

### PR DESCRIPTION
**Pull request by jpgill86**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
You became clearly the project leader!!
If you need any help tell me boss.

**Comment by jpgill86** [comment]
@samuelgarcia, I think there is something you could do that I cannot: Could you add me as a maintainer on ReadTheDocs.org? My username is jpgill86.

https://readthedocs.org/dashboard/ephyviewer/users/

I plan to enable old versions of the docs in case I or anyone ever needs to refer to them.

**Comment by samuelgarcia** [comment]
Done.

**Comment by jpgill86** [comment]
Thanks Samuel!

**Pull request merged**
