### PR TITLE
Added fallback icons for play and stop buttons

### PR DESCRIPTION
**Pull request by jpgill86**
Since `QIcon.fromTheme` works only on systems for which Qt-compatible themes are installed (some Linux systems, but not Windows or Mac, I think), icons may fail to load for the play and stop buttons. This commit provides fallback icons in case the icons cannot be loaded from a theme.

### CODE REVIEW

**Comment by jpgill86** [comment]
My original approach to adding the icon files to the package was different and more complicated. I got so far as getting the icons to load correctly on my system, but I couldn't figure out how to package the icons with ephyviewer. For reference, here's my original approach, which was based on some tutorials I found.

I created a file called `resources.qrc` in the same directory as `navigation.py` and the `icons` directory, and I filled it with the following:

    <!DOCTYPE RCC><RCC version="1.0">
    <qresource>
        <file>icons/play-icon.png</file>
        <file>icons/stop-icon.png</file>
    </qresource>
    </RCC>

On my system, I have PyQt5 installed. With it comes a command line tool named `pyrcc5` which can be used to compile the `qrc` file into a Python module containing byte-code representation of the icons. By running

    pyrcc5 -o resources.py resources.qrc

and importing the resulting module in `navigation.py`,

    from . import resources

the icons could be make available to the [Qt Resource System](http://doc.qt.io/qt-5/resources.html).

The lines that load the icons in `navigation.py` were then a little simpler:

    but = QT.QPushButton(icon=QT.QIcon.fromTheme('media-playback-start', QT.QIcon(':/icons/play-icon.png')))

    but = QT.QPushButton(icon=QT.QIcon.fromTheme('media-playback-stop',  QT.QIcon(':/icons/stop-icon.png')))

where the `:` signifies that the file can be accessed through the Qt Resource System.

Although this approach worked for the local installation on my system, I realized that I wasn't sure how to handle the `pyrcc5` step for packaging and distribution, and I couldn't find any tutorials on it. Ideally, the icon files and `qrc` file would be checked into version control, but the generated file `resources.py` would not be. For this to work, the install process for ephyviewer would have to invoke `pyrcc5` or something equivalent on the end-user's system. ephyviewer is currently flexible enough to work with PyQt4 as well, which has a different command line utility (`pyrcc4`).

How to instruct `pip` to handle all of this complexity was unclear to me, so I opted for the much simpler approach of using a relative path for locating the icon files. Seems to work well!

**Comment by samuelgarcia** [comment]
Hi.
In all my Qt project I deal with icons and ressource with this kinf of approach:
https://github.com/samuelgarcia/tridesclous/tree/master/tridesclous/gui/icons

In short, when I add a new icons:
  1. I add it to ...../icons/png/
  2. Lauch "mak_ressource.py" that auto construct the qrc file
  3. test it with "test_ressource.py"
  4. add the new icon + all chnaged file in git.


If you don't mind. I would prefer to push this to master on my side soon.
It would cancel this PR but after you would be able to any icons where you want.

is it OK ?

**Comment by jpgill86** [comment]
That sounds great, go for it!

**Comment by samuelgarcia** [comment]
I would implement icon features soon, I swear it :)

**Comment by samuelgarcia** [comment]
See #46.

I close this.

**Pull request closed without merging**
