### PR TITLE
Prepare release 1.2.0

### PR DESCRIPTION
**Pull request by jpgill86**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
Well done!
Sorry I have few time for ephyviewer theses times.

**Comment by jpgill86** [comment]
No problem! It has been working very smoothly for me. I continue to use ephyviewer almost every day!

I don't suppose you'll be at the SfN meeting later this month, will you? I'd be happy to meet up, if only so that I could say thanks! I will probably reserve a some space on my poster for plugging neurotic/ephyviewer, or at least have handouts or something, haha.

**Comment by samuelgarcia** [comment]
No I won't be at SFN.
I would be also happy to meet you.
Next time maybe.

**Comment by jpgill86** [comment]
Understandable. It's quite a hike from Lyon to Chicago!

**Comment by samuelgarcia** [comment]
Every year, since 10 year,  I want to come at SFN. And every year I postpone to the folowing year, waiting to have seomthing "strong" to present.
Maybe next year.
Enjoy, you should go for the poster of spike interface!! I participate for the work.

**Comment by jpgill86** [comment]
Haha, you said the say thing last year. 😜 But that's reasonable.

"Neural oscillations in olfactory and memory regions predict episodic odor memory richness: Unraveling the Proust phenomenon"? Looks very interesting! Unfortunately I will be leaving the conference a day early and will miss it. 😞

**Comment by samuelgarcia** [comment]
Smart!

**Pull request merged**
