### PR TITLE
Add scatter_size as an adjustable parameter to TraceViewer

### PR DESCRIPTION
**Pull request by jpgill86**
The new `scatter_size` param for `TraceViewer` controls the size of scatter plot points (drawn only when the source is an `AnalogSignalSourceWithScatter`). The parameter can be set at initialization (`TraceViewer(..., scatter_size=5)`) and using the global options window (double click on trace window).

### CODE REVIEW

**Comment by samuelgarcia** [comment]
you are back!
thank you.
Not so happy to have it at __init__ level

**Comment by jpgill86** [comment]
I am back! I've had my nose to the grindstone for the past few weeks, preparing for the SfN meeting next week. (By the way, will you be there? I'd like to shake your hand and thank you in person for ephyviewer, haha.) Sorry I haven't responded to your other requests for comment here and elsewhere, I promise I'll get to them when I have a little more time!

I'll revise the PR to not add the new param in the `__init__` method.

**Comment by samuelgarcia** [comment]
Unfortunatly I won't be at SFN.
I promise myself since 6 years to prepare something for SFN at methods session , but I never did it.
I should present real time spike sorting before there to much competitors.
Presenting neo there should be a good idea to.

Thank you for the change.

**Comment by jpgill86** [comment]
Yes, those do sound like good ideas!

Thanks for the merge!

**Pull request merged**
