### PR TITLE
Add back channel_indexes in AnalogSignalFromNeoRawIOSource

### PR DESCRIPTION
**Pull request by samuelgarcia**
Add back channel_indexes in AnalogSignalFromNeoRawIOSource after neo 0.10

#156

### CODE REVIEW

**Comment by samuelgarcia** [comment]
@jpgill86 : does this would restore the channel selection in `AnalogSignalFromNeoRawIOSource`.
I haven"t really tested. It is a draft proposal, tell me is this will break too much code or not.

Note that we could also have `stream_index=None` in the signature and if there is only unique stream then stream_indexd is automitically set. It could simplify and would have the same feeling than before no ?

**Comment by jpgill86** [comment]
The code works! Thank you Sam! This clarifies things for me a lot, and I see now that the stream concept was actually much simpler than I thought. And a good idea to add to Neo, even if people like me were confused about it at first, haha.

I think adding a default for `stream_index` is a good idea. I can implement that and push it here in a moment.

**Comment by jpgill86** [comment]
What do you think of a34aee2?

I made one change for the sake of backwards compatibility: I put the `channel_indexes` argument before the `stream_index` argument. For people like me who [didn't have the foresight to pass the `channel_indexes` argument using a keyword](https://github.com/jpgill86/neurotic/blob/2f1cba4c7df4f21e32d7c29f5d80c76662372f3b/neurotic/gui/config.py#L356), ephyviewer will remain backwards compatible if we use this ordering. However, I will admit it's a bit awkward since streams are higher in the hierarchy than channels. Do you think this is a good idea for the sake of backwards compatibility?

**Comment by jpgill86** [comment]
Maintaining support for Neo going back two versions is a good idea. I think we should check the version of Neo in `AnalogSignalFromNeoRawIOSource` and `SpikeFromNeoRawIOSource` and use whatever implementation is needed, i.e., with or without `signal_streams`, and with either `unit_channels` or `spike_channels`.

If you like that plan, I can build it. Perhaps this PR should be merged first though.

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
OK for inverting kargs order if it keep your copatibility.

And yes we could have version checking in init for better error handling.

Noramally the  `get_sources_from_neo_rawio()` route the correct class for the correct neo version but for direct use it can be usefull.

**Comment by jpgill86** [comment]
Great, I'll get to work on that.

**Comment by jpgill86** [comment]
Do you want to merge this PR first?

**Comment by jpgill86** [comment]
I'm going to go ahead with the merge, then open a new PR for the more backwards-compatible implementation.

**Pull request merged**
