### PR TITLE
[WIP] Compatibility fixes for Neo RawIO streams

### PR DESCRIPTION
**Pull request by jpgill86**
See  NeuralEnsemble/python-neo#949

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Thank youi for this.

I think we should also add stream_index or stream_id in 
```
class AnalogSignalFromNeoRawIOSource(BaseAnalogSignalSource):
    def __init__(self, neorawio, stream_index=None, channel_indexes=None):
```
stream_index=None would be stream_index=0 if only one stream avaliable and raise error when several streams.

**Comment by samuelgarcia** [comment]
and also in ```get_sources_from_neo_rawio()```

this
```
        try:
            # Neo >= 0.9.0
            channel_indexes_list = neorawio.get_group_signal_channel_indexes()
        except AttributeError:
            # Neo < 0.9.0
            channel_indexes_list = neorawio.get_group_channel_indexes()
        for channel_indexes in channel_indexes_list:
            #one soure by channel group
            sources['signal'].append(AnalogSignalFromNeoRawIOSource(neorawio, channel_indexes))
```
will explicitly loop over stream_index.

i will do it when the PR in neo will be merge.

The release is not for now.

**Comment by jpgill86** [comment]
OK, this will probably make more sense to me once I've familiarized myself with the Neo PR!

**Comment by samuelgarcia** [comment]
I started something  in #151 .
I close this.

**Pull request closed without merging**
