### PR TITLE
Add long description and project URLs to PyPI metadata

### PR DESCRIPTION
**Pull request by jpgill86**

### CODE REVIEW

**Comment by jpgill86** [comment]
This looks better now 😊

https://pypi.org/project/ephyviewer/1.1.1/

**Comment by samuelgarcia** [comment]
Hi Jeffrey, you should put your name in authors in setup.py to appear in pypi.

**Comment by jpgill86** [comment]
The `author` and `author_email` fields of `setup.py` do not allow lists and can only take strings ([source](https://stackoverflow.com/questions/9999829/how-to-specify-multiple-authors-emails-in-setup-py)).

I first tried concatenating our names and emails into single strings as was suggested [here](https://stackoverflow.com/a/10005265/3314376), but that produced a single bad email link: https://test.pypi.org/project/ephyviewer/0.0.102/#description

I then tried dropping the `author_email` field and inserting our emails in plain text in the `author` field: https://test.pypi.org/project/ephyviewer/0.0.105/#description

Finally I tried what you've done with tridesclous and tossed out the emails entirely, using just plain text names: https://test.pypi.org/project/ephyviewer/0.0.106/#description

Do you have a preference between the latter options? I think I prefer the last since it's clean. Our contact information can be found elsewhere, probably, and the PyPI metadata contains a direct link to the issue tracker, so it's easy to notify us of bugs. What do you think?

**Comment by samuelgarcia** [comment]
I also prefer teh second one with concatenated names but without emails.

**Pull request merged**
