### PR TITLE
Prepare release 1.5.0

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
I would like to make a release but tests are still crashing on github.
I don't known what happen.
On my machine locally with PyQt5/python3.8 it works with same package version.
Theses remote crash are more complicated than standard python fails. I guess theses are C++/Qt5 stuff.
If you have time to pull this and test it on your local machine maybe you could help a bit.
Any idea ?

**Comment by samuelgarcia** [comment]
What about pytest-qt or pytest-xvfb ?

**Comment by jpgill86** [comment]
Hi Sam. Luckily I have time to look at this today! I'll get back to you.

**Comment by jpgill86** [comment]
> What about pytest-qt or pytest-xvfb ?

Regarding pytest-xvfb, I tried that some months ago in a private branch from my unmerged PyQt6 PR (#147): https://github.com/jpgill86/ephyviewer/commit/7af30707e40e86bef8ba24ca19b2f08c3dd61d0b. The tests did not pass at the time.

It has been so long that I don't really remember, but I think I was planning on waiting for #147 to be completed and merged before introducing pytest-xvfb on top of it. Of course, if it fixes the problem here, there is no reason I can see to wait.

I will continue to look into the failing tests, but I thought I'd mention my prior encounter with pytest-xvfb.

**Comment by jpgill86** [comment]
I fixed the failing tests on the master branch in #155. It came down to a fix on one line of code, needed to work around a bug in Matplotlib.

You should merge or rebase this branch with master.

**Comment by samuelgarcia** [comment]
Thank you so much!!!!
I will rebease I let you modify the changelog if you want and we could release this week.
Then maybe we can integrate the PyQt6.

**Comment by samuelgarcia** [comment]
@jpgill86 : I think this is readey to merge. Then you can tag for relase. Tell me if it is OK for you.

Thank you so much again for the very hard debug.

**Comment by jpgill86** [comment]
Hi @samuelgarcia,

I'm so glad it worked!

I have a few things I'd like to tweak. In particular, we can remove `pytest-xvfb` from `requirements-tests.txt`, but I'd like to modify the change log, the installation instructions, and maybe more.

Would you be willing to check the "Allow edits and access to secrets by maintainers" box in the right column of this PR?

**Comment by jpgill86** [comment]
Would it be a problem for you if we rename these classes?

* `FromSpikeinterfaceRecordingSource` --> `SpikeInterfaceRecordingSource`, to be more consistent with other class names and to capitalize the i.
* `FromSpikeinterfaceSorintgSource` --> `SpikeInterfaceSortingSource`, same reason, and to correct a spelling error.

You know SpikeInterface and I don't, so you'll know better whether the "From" is needed here. Compare to `NeoAnalogSignalSource`, etc.

**Comment by jpgill86** [comment]
Do we want to require Neo >= 0.10 now?

**Comment by jpgill86** [comment]
Should [this](https://github.com/NeuralEnsemble/ephyviewer/blob/094c6b81fd42bb2378332adc7b76f6ed609662e7/ephyviewer/datasource/spikeinterfacesources.py#L14) require SpikeInterface 0.90.1 instead of 0.90.0? From the [SI release notes](https://github.com/SpikeInterface/spikeinterface/blob/7d2b3bdafbbabfbbbeede5e4c344821e8f5ec927/doc/releases/0.90.1.rst), it looks like `__version__` wasn't exposed before 0.90.1.

**Comment by jpgill86** [comment]
An example for the docs of how to use the SpikeInterface sources would be nice, but if you want to get the release out as soon as possible, I understand.

**Comment by samuelgarcia** [comment]
Hi Jeffrey,
I agree with all you comments. Thank you for the deep check.
I will make a spikeinterface example today.

About neo version in code and doc mayube we could keep (version - 0.2) so 0.8. What do you think it flexible to be compatible with some older version, no ?

**Comment by jpgill86** [comment]
@samuelgarcia, could you rebase/merge master now? We can then update the release notes, and then finally release. Almost there!

**Comment by samuelgarcia** [comment]
OK I merge with master stuff.

I let you update release notes ?

Thank you very much for all the time on this!!

**Comment by jpgill86** [comment]
Yes, I will take care of the notes. Is it alright if I go ahead with the release too?

**Comment by samuelgarcia** [comment]
Yes. You are the official boss now! Don't need to ask. :)

**Comment by jpgill86** [comment]
@samuelgarcia, the release is done!

https://pypi.org/project/ephyviewer/

The new GitHub Actions for publishing to PyPI worked perfectly. I've updated my release instructions to include those new steps:

https://github.com/NeuralEnsemble/ephyviewer/wiki/Creating-a-release

**Comment by samuelgarcia** [comment]
Congratulation for your hard work. I was supposed to do it!!

Can the conda be more automed with a github actions ?

**Comment by jpgill86** [comment]
> Can the conda be more automed with a github actions ?

Something we could do is this: #163

**Pull request merged**
