### PR TITLE
Start integrate neo v0.10 with channel streams.

### PR DESCRIPTION
**Pull request by samuelgarcia**

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeffrey.
I started this for the futur neo release.
tell me what do you think ?

**Comment by samuelgarcia** [comment]
pypi is down, this is why all tests fails

**Comment by samuelgarcia** [comment]
@jpgill86 
Hi Jeffrey,
we will release neo next Monday. 
I would need to merge et release this PR just immediatly after because I give a python course next week that will depend on neo+ephyviewer.

Does this PR looks good to you ?
When tests will pass can I merge and release ?

**Comment by jpgill86** [comment]
I'm very sorry Sam that I haven't been able to find the time recently to review this. If you are happy with it, please merge and release to your liking!

**Comment by samuelgarcia** [comment]
@jpgill86 
Test are failling on GH but working on my machine.
I really need soon and don't have time to understand why. It is deep inside PyQt5 I think.
I merge this anyway.
Sorry.

**Pull request merged**
