### PR TITLE
Pyside6

### PR DESCRIPTION
**Pull request by samuelgarcia**
add pyside6 only

PyQt6 have several problem (icons, RightDockWidgetArea not findable ...)

### CODE REVIEW

**Comment by samuelgarcia** [comment]
Hi Jeffrey, I am back on this.
I will need pyside6 working soon.
I now works with recent pyqtgraph.

I take your history and created a new PR on my repo.
Tell me if you want to test this.

**Comment by samuelgarcia** [comment]
@jpgill86 test are passing.
pyside6 works locally for me.
I would propose to merge this soon.
Is it OK ?
And also we could make a release.
It would help a user I know that want ephyviewer + spikeinterface-gui + pyside6 in the same env.

**Comment by samuelgarcia** [comment]
I hope that no answer means, "even if I am quite busy I am totally ok". So merging.

**Comment by jpgill86** [comment]
@samuelgarcia, I'm very sorry for the silence! You inferred correctly, I've been very busy, and I'm happy you went ahead with the merge!

**Pull request merged**
